### ISSUE TITLE
Make Drive Base

### ISSUE THREAD

**Issue by TaeSeanDo** [TeamCautionRobotics/2020-FRC-robot#1]
A DriveBase class must be made, complete with encoders and a gyro.

**Comment by docprofsky** [comment]
Gyro is a definite yes. It just plugs into the roboRIO and most or all of our roboRIOs have one plugged into them.

**Comment by TaeSeanDo** [comment]
I don't know what you're talking about. Did I imply the gyro was unnecessary to code? </sarcasm>

**Comment by docprofsky** [comment]
I also do not know what I was talking about.

**Comment by TaeSeanDo** [comment]
But you see Schuyler, the “if necessary” part definitely never existed and I definitely did not delete it after your comment
