### ISSUE TITLE
Use all the classes to control the robot in Robot.java teleop

### ISSUE THREAD

**Issue by TaeSeanDo** [TeamCautionRobotics/2020-FRC-robot#16]
- [x] Drive Base (tank drive for now, plus piston for shifting low to high speed)
- [x] Harvester (2 motors)
- [x] BallChucker9000 (3 motors, 1 piston)
- [x] Climb (2 motors, 1 piston)
All other non-auto MVP issues must be addressed first. Ports on the roboRIO and driver controls will be addressed later. Code with arbitrary port and button values still closes this issue.

**Comment by docprofsky** [comment]
We also need to address #21 first too, in addition, as well.
